//
// Created by covald on 23.01.24.
//

#ifndef STRUCTURE_PROGRAMMING_PROJECT_AUTH_SETTINGS_H
#define STRUCTURE_PROGRAMMING_PROJECT_AUTH_SETTINGS_H

#endif //STRUCTURE_PROGRAMMING_PROJECT_AUTH_SETTINGS_H
#define cls "clear"